name: Fetch-upstream
on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '5'

    - name: Fetch upstream (dirty hacks)
      run: |
        git reset --soft HEAD^^^^
        git pull git://git.savannah.gnu.org/nano.git
        git -c user.email='mail@beuke.org' -c user.name='Fabian Beuke' commit \
          -m 'Merge pull request #8 from davidhcefx/patch-2' \
          -m 'Automatically fetch GNU nano upstream (fix PR issue)'
        git push --force

